name: BuildOnly

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Setup dotnet 6 / 7 / 8'
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: | 
          6.0.x
          7.0.x
          8.0.x

      - name: 'Setup Java JDK 11'
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'microsoft'
          java-version: '11'
        
      - name: 'Add MSBuild to PATH'
        uses: microsoft/setup-msbuild@v2.0.0
        with:
          vs-prerelease: true

      - name: 'Install DotNet workloads'
        shell: bash
        run: |
          dotnet workload install android ios tvos macos maui maccatalyst

      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}

      - name: 'Restore and Compile and Extract DynamicData Projects to produce content for API and custom md files based on the source'
        run: ./build.cmd CreateContent
        
      - name: 'Build DynamicData Website'
        run: ./build.cmd BuildWebsite